### ISSUE TITLE
Don't know how to test my code

### ISSUE THREAD

**Issue by hwankyusong** [CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment#4]
I'm not sure how to test the code we wrote.

Simply running main.py returns the error:
ModuleNotFoundError: No module named 'pyscf'

And running the main.py while in the virtual environment returns another pyscf-related error:
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from pyscf import gto  # PySCF is a quantum chemistry python module
  File "/Users/hwankyusong/Desktop/HF_SCF_Assignment/venv/lib/python3.8/site-packages/pyscf/__init__.py", line 71, in <module>
    from pyscf import lib
  File "/Users/hwankyusong/Desktop/HF_SCF_Assignment/venv/lib/python3.8/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/Users/hwankyusong/Desktop/HF_SCF_Assignment/venv/lib/python3.8/site-packages/pyscf/lib/numpy_helper.py", line 27, in <module>
    from pyscf.lib import misc
  File "/Users/hwankyusong/Desktop/HF_SCF_Assignment/venv/lib/python3.8/site-packages/pyscf/lib/misc.py", line 46, in <module>
    h5py.get_config().default_file_mode = 'a'
  File "h5py/h5.pyx", line 179, in h5py.h5.H5PYConfig.default_file_mode.__set__
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead.

**Comment by shots47s** [comment]
Were you able to install the modules? 

`pip install -r requirements.txt`.

See issue #1 for reference.

**Comment by hwankyusong** [comment]
Yes, I installed the modules.

**Comment by hwankyusong** [comment]
Perhaps I'm running the files incorrectly. What is the correct command line to run main and SCF?

**Comment by shots47s** [comment]
`python main.py` should do it. Assuming you are in your active virtual environment.

Ok, I will do a functional test myself and get back to you asap. You should be able to run main.py and it work, there appears to be some module incompatibility issues.

**Comment by shots47s** [comment]
I believe I fixed this, see #5.
