### ISSUE TITLE
Getting an error with PySCF 1.7.2 in h5py.

### ISSUE THREAD

**Issue by shots47s** [CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment#5]
Because of the change to PySCF version, the version of h5py was not compatible. 

The error message was: 

```python
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from pyscf import gto  # PySCF is a quantum chemistry python module
  File "/mnt/c/Users/shawn/Programs/ms-das/test/HF_SCF_Assignment/vevn/lib/python3.7/site-packages/pyscf/__init__.py", line 71, in <module>
    from pyscf import lib
  File "/mnt/c/Users/shawn/Programs/ms-das/test/HF_SCF_Assignment/vevn/lib/python3.7/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/mnt/c/Users/shawn/Programs/ms-das/test/HF_SCF_Assignment/vevn/lib/python3.7/site-packages/pyscf/lib/numpy_helper.py", line 27, in <module>

    from pyscf.lib import misc
  File "/mnt/c/Users/shawn/Programs/ms-das/test/HF_SCF_Assignment/vevn/lib/python3.7/site-packages/pyscf/lib/misc.py", line 46, in <module>
    h5py.get_config().default_file_mode = 'a'
  File "h5py/h5.pyx", line 179, in h5py.h5.H5PYConfig.default_file_mode.__set__
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead.
```

**Comment by shots47s** [comment]
The fix was to edit requirements.txt to use an older version of h5py.

See 7d23394

You will need to sync with the main repository, see #1.

**Comment by shots47s** [comment]
Note, it will print out a warning, that you can ignore.
